name: Build PS-Okta Module
on:
  push:
    branches: [Development]
defaults:
  run:
    shell: pwsh
  runs-on: ubuntu-latest

jobs:
  build-module:
    steps:
      - uses: actions/checkout@v3

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: ModuleBuilder, platyPS

      - name: Build Module
        run: |
          ./Start-ModuleBuild.ps1
          ./Start-NugetBuild.ps1