name: Build PS-Okta Module
on:
  push:
    branches: [Development]
defaults:
  run:
    shell: pwsh

jobs:
  build-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: ModuleBuilder, platyPS
          updatable: "true"

      - name: Show that the Action works
        shell: powershell
        run: |
          Get-Module -Name ModuleBuilder, platyPS -ListAvailable | Select Path
          Import-Module ModuleBuilder

      - name: Build Module
        run: |
          ./Start-ModuleBuild.ps1
          ./Start-NugetBuild.ps1