name: build-ps-okta-module

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - devlopment

jobs:
  validate:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
